# Generated by Django 5.2.7 on 2026-07-30 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.UUIDField()),
                ('predicate', models.CharField(choices=[('name', 'Name'), ('house_name', 'House name'), ('birth_year', 'Birth year'), ('death_year', 'Death year'), ('is_living', 'Is living'), ('parent_of', 'Parent of'), ('sibling_of', 'Sibling of'), ('partner_of', 'Partner of'), ('sibling_order', 'Sibling order'), ('photo_tag', 'Person in photo'), ('other', 'Other')], max_length=40, verbose_name='predicate')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='value')),
                ('confidence', models.FloatField(default=1.0, verbose_name='confidence')),
                ('confirmations_count', models.PositiveIntegerField(default=0, verbose_name='confirmations')),
                ('disputes_count', models.PositiveIntegerField(default=0, verbose_name='disputes')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('contested', 'Contested'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=16, verbose_name='status')),
                ('resolution_note', models.TextField(blank=True, verbose_name='arbiter note')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_claims', to=settings.AUTH_USER_MODEL)),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'claim',
                'verbose_name_plural': 'claims',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='claims_clai_subject_1fca92_idx'), models.Index(fields=['predicate', 'status'], name='claims_clai_predica_809c6a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), name='claim_confidence_in_range')],
            },
        ),
    ]
