# Generated by Django 5.2.7 on 2026-07-30 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('canonical', 'Canonical'), ('merged_into', 'Merged into another person'), ('tombstone', 'Tombstone (created in error)')], db_index=True, default='canonical', max_length=16, verbose_name='status')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('name_ml', models.CharField(blank=True, max_length=200, verbose_name='name (Malayalam)')),
                ('nicknames', models.JSONField(blank=True, default=list, verbose_name='nicknames')),
                ('house_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='house name')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=16, verbose_name='gender')),
                ('is_living', models.BooleanField(default=True, verbose_name='is living')),
                ('birth_year_min', models.IntegerField(blank=True, null=True, verbose_name='birth year (earliest)')),
                ('birth_year_max', models.IntegerField(blank=True, null=True, verbose_name='birth year (latest)')),
                ('birth_date_exact', models.DateField(blank=True, null=True, verbose_name='birth date (exact)')),
                ('death_year_min', models.IntegerField(blank=True, null=True, verbose_name='death year (earliest)')),
                ('death_year_max', models.IntegerField(blank=True, null=True, verbose_name='death year (latest)')),
                ('death_date_exact', models.DateField(blank=True, null=True, verbose_name='death date (exact)')),
                ('place_origin', models.CharField(blank=True, max_length=200, verbose_name='place of origin')),
                ('place_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('place_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('religion_community', models.CharField(blank=True, max_length=120, verbose_name='religion / community')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='institution')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('visibility_consent', models.BooleanField(default=False, verbose_name='consents to be publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='genealogy.person', verbose_name='merged into')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'ordering': ('name_en', 'name_ml', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('union_type', models.CharField(choices=[('marriage', 'Marriage'), ('partnership', 'Partnership'), ('unknown', 'Unknown')], default='marriage', max_length=16, verbose_name='union type')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='year (earliest)')),
                ('year_max', models.IntegerField(blank=True, null=True, verbose_name='year (latest)')),
                ('date_exact', models.DateField(blank=True, null=True, verbose_name='date (exact)')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='place')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('unknown', 'Unknown')], default='unknown', max_length=16, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'union',
                'verbose_name_plural': 'unions',
                'ordering': ('year_min', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='UnionMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('partner', 'Partner'), ('child', 'Child')], max_length=16, verbose_name='role')),
                ('relation_type', models.CharField(choices=[('biological', 'Biological'), ('adopted', 'Adopted'), ('step', 'Step'), ('unknown', 'Unknown')], default='biological', max_length=16, verbose_name='relation type')),
                ('sibling_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='sibling order')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_memberships', to='genealogy.person')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='genealogy.union')),
            ],
            options={
                'verbose_name': 'union membership',
                'verbose_name_plural': 'union memberships',
                'ordering': ('role', 'sibling_order', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status', 'is_living'], name='genealogy_p_status_a3e105_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['birth_year_min', 'birth_year_max'], name='genealogy_p_birth_y_35aeb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merged_into__isnull', False), ('status', 'merged_into')), models.Q(models.Q(('status', 'merged_into'), _negated=True), ('merged_into__isnull', True)), _connector='OR'), name='person_merged_into_requires_status'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('birth_year_min__isnull', True), ('birth_year_max__isnull', True), ('birth_year_min__lte', models.F('birth_year_max')), _connector='OR'), name='person_birth_year_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('death_year_min__isnull', True), ('death_year_max__isnull', True), ('death_year_min__lte', models.F('death_year_max')), _connector='OR'), name='person_death_year_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into', models.F('id')), _negated=True), name='person_not_merged_into_self'),
        ),
        migrations.AddConstraint(
            model_name='union',
            constraint=models.CheckConstraint(condition=models.Q(('year_min__isnull', True), ('year_max__isnull', True), ('year_min__lte', models.F('year_max')), _connector='OR'), name='union_year_range_ordered'),
        ),
        migrations.AddIndex(
            model_name='unionmembership',
            index=models.Index(fields=['person', 'role'], name='genealogy_u_person__827914_idx'),
        ),
        migrations.AddIndex(
            model_name='unionmembership',
            index=models.Index(fields=['union', 'role'], name='genealogy_u_union_i_79945e_idx'),
        ),
        migrations.AddConstraint(
            model_name='unionmembership',
            constraint=models.UniqueConstraint(fields=('union', 'person', 'role'), name='unique_union_person_role'),
        ),
    ]
