# Generated by Django 5.2.7 on 2026-07-30 12:57

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    """Fuzzy name search.

    The gin_trgm_ops opclasses below need the pg_trgm extension, so it is enabled in the
    same migration rather than left as an undocumented manual step on a fresh database.
    """

    dependencies = [
        ('genealogy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='person_name_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ml'], name='person_name_ml_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['house_name'], name='person_house_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nicknames'], name='person_nicknames_gin'),
        ),
    ]
