# Generated by Django 5.2.7 on 2026-07-30 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('audio', 'Audio'), ('document', 'Document')], max_length=16, verbose_name='type')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='file')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='year (earliest)')),
                ('year_max', models.IntegerField(blank=True, null=True, verbose_name='year (latest)')),
                ('transcript', models.TextField(blank=True, verbose_name='transcript')),
                ('transcript_language', models.CharField(blank=True, max_length=8, verbose_name='transcript language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to=settings.AUTH_USER_MODEL)),
                ('persons', models.ManyToManyField(blank=True, related_name='media_items', to='genealogy.person', verbose_name='tagged persons')),
            ],
            options={
                'verbose_name': 'media item',
                'verbose_name_plural': 'media items',
                'ordering': ('-created_at',),
            },
        ),
    ]
