# Generated by Django 5.2.7 on 2026-07-30 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0, verbose_name='score')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='evidence')),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('rejected', 'Not a duplicate')], db_index=True, default='open', max_length=16, verbose_name='status')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_candidates_as_a', to='genealogy.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_candidates_as_b', to='genealogy.person')),
            ],
            options={
                'verbose_name': 'merge candidate',
                'verbose_name_plural': 'merge candidates',
                'ordering': ('-score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MergeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField(default=dict, verbose_name='pre-merge snapshot')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='performed at')),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='reverted at')),
                ('absorbed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_as_absorbed', to='genealogy.person', verbose_name='absorbed')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_records', to='merging.mergecandidate')),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_absorbed', to='genealogy.person', verbose_name='canonical')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_merges', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_merges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'merge record',
                'verbose_name_plural': 'merge records',
                'ordering': ('-performed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='mergecandidate',
            constraint=models.UniqueConstraint(fields=('person_a', 'person_b'), name='unique_merge_candidate_pair'),
        ),
        migrations.AddConstraint(
            model_name='mergecandidate',
            constraint=models.CheckConstraint(condition=models.Q(('person_a', models.F('person_b')), _negated=True), name='merge_candidate_distinct_persons'),
        ),
        migrations.AddIndex(
            model_name='mergerecord',
            index=models.Index(fields=['absorbed', 'reverted_at'], name='merging_mer_absorbe_694ad4_idx'),
        ),
    ]
